name: Statistical Models
markdown: redcarpet
pygments: true
baseurl: /Book
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"